### ISSUE TITLE
Request for release into indigo

### ISSUE THREAD

**Issue by UltronDestroyer** [ros/convex_decomposition#1]
It is required for the pr2_common stack https://github.com/PR2/pr2_common #234

**Comment by dirk-thomas** [comment]
I don't think there is currently an active maintainer for this package. If you depend on it it might make sense to take the maintainer role for it. I can certainly give you access to this repo as well as to the corresponding gbp?

**Comment by UltronDestroyer** [comment]
The wiki mentioned  Ioan Sucan <isucan AT willowgarage DOT com> as a maintainer. However that may be setup from his WG days... @isucan Do you still maintain this?

**Comment by isucan** [comment]
If someone is willing to release this, I would happy :)  otherwise I can do
it ad well.

**Comment by UltronDestroyer** [comment]
Well, who wants to do it then? Looks like the PR2 is the only user of this package.. kinda falls on me eh.

**Comment by tfoote** [comment]
You could email ros-release to see if you can get a volunteer for the orphan package.

**Comment by UltronDestroyer** [comment]
That would be a good idea. Where should the location of this package go? It seems that only the pr2 requires it, so the pr2 repository would make sense.

**Comment by dirk-thomas** [comment]
There is no need to move the repository. Whoever will be working on it can get the necessary permissions. (But of course the maintainer can choose whatever he prefers.)

**Comment by BryceVoort** [comment]
I'll step in as the active maintainer of this package.

**Comment by UltronDestroyer** [comment]
awesome! @dirk-thomas can @BryceVoort get the permissions to access this package?

**Comment by dirk-thomas** [comment]
Thank you for stepping in. I have added you @BryceVoort as an admin for this repo as well as the corresponding release repo.

**Comment by davetcoleman** [comment]
Should this be closed now that its been released?

**Comment by wjwwood** [comment]
It has been released, thanks for the bump @davetcoleman.
