### ISSUE TITLE
Release convex_decomposition into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros/convex_decomposition#11]
Would you mind releasing `convex_decomposition` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 29 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by k-okada** [comment]
thanks!, done  https://github.com/ros/rosdistro/pull/24554
