### ISSUE TITLE
Requesting ownership of this repo

### ISSUE THREAD

**Issue by UltronDestroyer** [ros/convex_decomposition#3]
@BryceVoort and I work together, he has given permission to transfer over it as he no longer maintains this package. 

I'll take it over to release for ROS Kinetic.

@wjwwood

**Comment by BryceVoort** [comment]
Approved to transfer ownership to @TheDash

**Comment by jackieokay** [comment]
@BryceVoort would you like to retain write permission to the repository?

**Comment by UltronDestroyer** [comment]
Thanks!

**Comment by BryceVoort** [comment]
@jacquelinekay not necessary. 
Thank you
